groups:
- name: alert_rules
  rules:      
    - alert: Production Endpoint Down
      expr: probe_success == 0
      for: 1m
      labels:
        severity: critical
      annotations:
        summary: "Production Endpoint {{ $labels.instance }} down"
        description: "{{ $labels.instance }} of job {{ $labels.job }} has been down for more than 1 minutes."

    - alert: Production Instance Down
      expr: up == 0
      for: 1m
      labels:
        severity: critical
      annotations:
        summary: "Production Instance {{ $labels.instance }} down"
        description: "{{ $labels.instance }} of job {{ $labels.job }} has been down for more than 1 minutes."

    - alert: StorageMaxedOut
      expr: node_filesystem_avail_bytes{mountpoint="/"}/node_filesystem_size_bytes{mountpoint="/"} < 0.2
      for: 5m
      labels:
        severity: critical
      annotations:
        summary: "Production Instance {{ $labels.instance }} storage is almost full"
        description: "The available storage on {{ $labels.instance }} is below 20%."  

    - alert: HighCPULoad
      expr: 100 - (avg by(instance) (irate(node_cpu_seconds_total{mode="idle"}[5m])) * 100) > 80
      for: 5m
      labels:
        severity: warning
      annotations:
        summary: "High CPU utilization on Production Instance {{ $labels.instance }}"
        description: "The CPU utilization on the EC2 instance {{ $labels.instance }} is above 80% for the last 5 minutes."

    - alert: HighMemoryUsage
      expr: (node_memory_MemTotal_bytes - node_memory_MemAvailable_bytes) / node_memory_MemTotal_bytes * 100 > 80
      for: 5m
      labels:
        severity: warning
      annotations:
        summary: "High Memory Usage on Production Instance {{ $labels.instance }}"
        description: "The Memory Usage on the EC2 Production Instance {{ $labels.instance }}is above 80% for the last 5 minutes."